services:
  - type: web
    name: rahim-portfolio
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn mw.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mw.settings
      - key: USE_POSTGRES
        value: "True"
      - key: DATABASE_URL
        value: postgresql://postgres:password@host:5432/postgres
      - key: DB_SSLMODE
        value: require
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
