# Generated by Django 6.0.7 on 2026-07-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='source_url',
            field=models.URLField(blank=True, help_text='GitHub or source code URL'),
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='Optional project screenshot or cover image URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Complete', 'Complete'), ('In Progress', 'In Progress'), ('Planned', 'Planned')], default='Complete', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True, help_text='Live preview URL'),
        ),
    ]
