# Generated by Django 6.0.7 on 2026-07-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0002_project_is_featured_project_source_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Rahim Portfolio', max_length=200)),
                ('hero_title', models.CharField(default="Hi, I'm Rahim.", max_length=200)),
                ('hero_text', models.TextField(default='I design and build modern web applications, portfolio sites, and digital experiences that help brands stand out online.')),
                ('about_title', models.CharField(default='About Me', max_length=200)),
                ('about_text', models.TextField(default="I'm a full-stack web developer with a passion for crafting beautiful interfaces and building robust backend systems. I love turning ideas into polished digital products that users enjoy.")),
                ('services_title', models.CharField(default='What I Do', max_length=200)),
                ('projects_title', models.CharField(default='Featured Projects', max_length=200)),
                ('contact_title', models.CharField(default='Contact Me', max_length=200)),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('footer_text', models.CharField(default='© 2026 Rahim Portfolio. All Rights Reserved.', max_length=255)),
            ],
            options={
                'verbose_name': 'Site Content',
                'verbose_name_plural': 'Site Content',
            },
        ),
    ]
