# Generated by Django 6.0.7 on 2026-07-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0003_sitecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='profile_intro_text',
            field=models.TextField(default='I am a passionate web developer skilled in Python, Django, HTML, CSS, and JavaScript. I enjoy creating clean user interfaces and efficient backend services.'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='profile_intro_title',
            field=models.CharField(default='Who I Am', max_length=200),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='profile_page_title',
            field=models.CharField(default='About Me', max_length=200),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='profile_skills_title',
            field=models.CharField(default='Skills', max_length=200),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='profile_work_text',
            field=models.TextField(default='I build portfolio websites, admin dashboards, and web apps with authentication, responsive design, and modern UX.'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='profile_work_title',
            field=models.CharField(default='What I Do', max_length=200),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='resume_contact_text',
            field=models.TextField(default='Email: youremail@example.com\nPhone: +92 300 0000000\nLocation: Pakistan'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='resume_contact_title',
            field=models.CharField(default='Contact', max_length=200),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='resume_education_text',
            field=models.TextField(default="Bachelor's in Computer Science, UET, 2021 - 2025"),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='resume_education_title',
            field=models.CharField(default='Education', max_length=200),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='resume_page_title',
            field=models.CharField(default='Resume', max_length=200),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='resume_summary_text',
            field=models.TextField(default='Experienced web developer specializing in Django, responsive design, and backend systems. Skilled at building polished, production-ready portfolio websites and dashboards.'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='resume_summary_title',
            field=models.CharField(default='Summary', max_length=200),
        ),
    ]
