# Generated by Django 6.0.7 on 2026-08-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0004_sitecontent_profile_intro_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('route_path', models.CharField(help_text='URL path without a leading slash, e.g. services or services/web-design', max_length=255, unique=True)),
                ('intro', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('hero_image_url', models.URLField(blank=True)),
                ('cta_label', models.CharField(blank=True, max_length=100)),
                ('cta_url', models.CharField(blank=True, help_text='Internal path or full URL', max_length=255)),
                ('show_in_nav', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
