"""
Django settings for mw project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')
load_dotenv(BASE_DIR / 'mw' / '.env')

def env_bool(name, default='False'):
    return os.environ.get(name, default).strip().lower() in {'1', 'true', 'yes', 'on'}


def env_list(name, default=''):
    value = os.environ.get(name, default)
    return [item.strip() for item in value.split(',') if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-^2tc6vqzl9tjaf6avrd+h8va4t@j^jswn1a84o%-t_!rs#h7=*')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DEBUG', 'True')

if os.getenv('VERCEL') or os.getenv('RENDER'):
    ALLOWED_HOSTS = ['.vercel.app' ]
else:
    ALLOWED_HOSTS = env_list('ALLOWED_HOSTS', '127.0.0.1., [::1]')
LOGIN_URL = '/admin/login/'

# Email settings for contact form and password reset
CONTACT_EMAIL = os.environ.get('CONTACT_EMAIL', '')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'webmaster@localhost')

# Use SMTP email backend when SMTP credentials are provided, otherwise fall back to file backend for development.
if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
else:
    EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.filebased.EmailBackend')
    EMAIL_FILE_PATH = BASE_DIR / 'sent_emails'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mw.myproject',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'mw.myproject.middleware.PageViewMiddleware',
]

ROOT_URLCONF = 'mw.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mw.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

USE_POSTGRES = env_bool('USE_POSTGRES', 'True' if os.getenv('DATABASE_URL') or os.getenv('DB_HOST') else 'False')
DATABASE_URL = os.getenv('DATABASE_URL', '').strip()
DB_SSLMODE = os.getenv('DB_SSLMODE', 'disable').strip().lower()
_DB_CONN_MAX_AGE = int(os.getenv('DB_CONN_MAX_AGE', 600))
_DB_CONN_HEALTH_CHECKS = env_bool('DB_CONN_HEALTH_CHECKS', 'True')
_DB_DISABLE_SERVER_SIDE_CURSORS = env_bool('DB_DISABLE_SERVER_SIDE_CURSORS', 'True' if os.getenv('VERCEL') else 'False')
_DB_CONNECT_TIMEOUT = int(os.getenv('DB_CONNECT_TIMEOUT', 10))

if DATABASE_URL and DATABASE_URL.startswith(('postgres://', 'postgresql://')):
    ssl_require = DB_SSLMODE in {'require', 'true', '1', 'yes', 'on'}
    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=_DB_CONN_MAX_AGE,
            conn_health_checks=_DB_CONN_HEALTH_CHECKS,
            disable_server_side_cursors=_DB_DISABLE_SERVER_SIDE_CURSORS,
            ssl_require=ssl_require,
        )
    }
    DATABASES['default'].setdefault('OPTIONS', {})['connect_timeout'] = _DB_CONNECT_TIMEOUT
elif USE_POSTGRES:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'portfolio_db'),
            'USER': os.getenv('DB_USER', 'postgres'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
            'CONN_MAX_AGE': _DB_CONN_MAX_AGE,
            'CONN_HEALTH_CHECKS': _DB_CONN_HEALTH_CHECKS,
            'DISABLE_SERVER_SIDE_CURSORS': _DB_DISABLE_SERVER_SIDE_CURSORS,
            'OPTIONS': {
                'sslmode': DB_SSLMODE,
                'connect_timeout': _DB_CONNECT_TIMEOUT,
            },
        }
    }
else:
    sqlite_path = BASE_DIR / 'db.sqlite3'
    if os.getenv('VERCEL'):
        sqlite_path = '/tmp/db.sqlite3'
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': sqlite_path,
        }
    }

SUPABASE_URL = os.getenv('SUPABASE_URL', '')
SUPABASE_ANON_KEY = os.getenv('SUPABASE_ANON_KEY', os.getenv('SUPABASE_KEY', ''))
SUPABASE_SERVICE_ROLE_KEY = os.getenv('SUPABASE_SERVICE_ROLE_KEY', '')

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Karachi'

USE_I18N = True

USE_TZ = True

if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = env_bool('SECURE_SSL_REDIRECT', 'False')
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'mw' / 'myproject' / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

if os.getenv('VERCEL'):
    STATIC_ROOT = '/tmp/staticfiles'
